import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';
import {useRouter} from "next/router"


function onSubmit(e) {
  e.preventDefault()
}


export function SignIn() {

  
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');


  return (
    <div>
      <form onSubmit={(e) => onSubmit(e)}>
        <input type="text" placeholder='username' onChange={(e) => setUsername(e.target.value)} />
        <input type="password" placeholder='password' onChange={(e) => setPassword(e.target.value)} />
<button type="submit">Log-In</button>      
      </form>
    </div>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <SignIn />

    </div>
  )
}
