import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import {useRouter} from "next/router"
import {useAuth} from '../utils/auth'



export function SignIn() {

  
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const { signIn, isSignedIn, signOut, authToken} = useAuth();


  function onSubmit(e) {
    e.preventDefault();
    signIn({username, password})
  }



  return (
    <div>
      <form onSubmit={(e) => onSubmit(e)}>
        <button onClick={(e) => (signOut())} type="button">signout</button>
{authToken ? (<p>Logged In</p>):(<span>Not Logged In</span>)}

        <input type="text" placeholder='username' onChange={(e) => setUsername(e.target.value)} />
        <input type="password" placeholder='password' onChange={(e) => setPassword(e.target.value)} />
<button type="submit">Log-In</button>      
      </form>
    </div>
  )
}

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <SignIn />

    </div>
  )
}
